import type { AppData } from "./types";
import {
  INBOX_ID,
  AIRCRAFT_ID,
  SHIPS_ID,
  RAIN_ID,
  ISS_ID,
  FIRE_ID,
  LIGHTNING_ID,
  METEORITE_ID,
  CABLE_ID,
  COVID_ID,
  NUCLEAR_ID,
  CRASH_ID,
  WRECK_ID,
  TECTONIC_ID,
  UNESCO_ID,
  AIR_ID,
  NUKETEST_ID,
  CO2_ID,
} from "./types";

// Initial data on first run (while localStorage is empty). A showcase of the
// live/data layers plus a couple of empty demo workspaces.
export function seedData(): AppData {
  return {
    activeWorkspaceId: METEORITE_ID,
    workspaces: [
      {
        id: INBOX_ID,
        name: "Inbox",
        icon: "📥",
        color: "#868e96",
        style: "dark-v11",
        pinned: false,
        marker: "circle",
        center: [0, 20],
        zoom: 1.5,
        layers: [
          { id: "lyr-inbox", name: "Notes", color: "#868e96", visible: true, features: [] },
        ],
      },
      {
        id: AIRCRAFT_ID,
        name: "Live Aircraft",
        icon: "✈️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-aircraft", name: "Flights", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: SHIPS_ID,
        name: "Live Ships",
        icon: "🚢",
        color: "#15aabf",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [4, 52],
        zoom: 7,
        layers: [
          { id: "lyr-ships", name: "Vessels", color: "#15aabf", visible: true, features: [] },
        ],
      },
      {
        id: RAIN_ID,
        name: "Rain",
        icon: "🌧️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-rain", name: "Radar", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: ISS_ID,
        name: "Space Station",
        icon: "🛰️",
        color: "#f783ac",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 2,
        layers: [
          { id: "lyr-iss", name: "ISS", color: "#f783ac", visible: true, features: [] },
        ],
      },
      {
        id: LIGHTNING_ID,
        name: "Lightning",
        icon: "⚡",
        color: "#facc15",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-lightning", name: "Strikes", color: "#facc15", visible: true, features: [] },
        ],
      },
      {
        id: METEORITE_ID,
        name: "Meteorites",
        icon: "☄️",
        color: "#f59e0b",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-meteorites", name: "Landings", color: "#f59e0b", visible: true, features: [] },
        ],
      },
      {
        id: FIRE_ID,
        name: "Wildfires",
        icon: "🔥",
        color: "#fb923c",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 25],
        zoom: 1.6,
        layers: [
          { id: "lyr-fires", name: "Active fires", color: "#fb923c", visible: true, features: [] },
        ],
      },
      {
        id: CABLE_ID,
        name: "Submarine Cables",
        icon: "🌐",
        color: "#22d3ee",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-cables", name: "Cables", color: "#22d3ee", visible: true, features: [] },
        ],
      },
      {
        id: COVID_ID,
        name: "COVID-19",
        icon: "🦠",
        color: "#dc2626",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 25],
        zoom: 1.6,
        layers: [
          { id: "lyr-covid", name: "Cases by country", color: "#dc2626", visible: true, features: [] },
        ],
      },
      {
        id: NUCLEAR_ID,
        name: "Nuclear Plants",
        icon: "☢️",
        color: "#4ade80",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-nuclear", name: "Reactors", color: "#4ade80", visible: true, features: [] },
        ],
      },
      {
        id: CRASH_ID,
        name: "Plane Crashes",
        icon: "🛩️",
        color: "#ef4444",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-crashes", name: "Accidents", color: "#ef4444", visible: true, features: [] },
        ],
      },
      {
        id: WRECK_ID,
        name: "Shipwrecks",
        icon: "⚓",
        color: "#2dd4bf",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-wrecks", name: "Wreck sites", color: "#2dd4bf", visible: true, features: [] },
        ],
      },
      {
        id: TECTONIC_ID,
        name: "Tectonics",
        icon: "🌋",
        color: "#f97316",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [150, 0],
        zoom: 1.6,
        layers: [
          { id: "lyr-tectonics", name: "Plates · Quakes · Volcanoes", color: "#f97316", visible: true, features: [] },
        ],
      },
      {
        id: UNESCO_ID,
        name: "UNESCO Sites",
        icon: "🏛️",
        color: "#eab308",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-unesco", name: "Heritage sites", color: "#eab308", visible: true, features: [] },
        ],
      },
      {
        id: AIR_ID,
        name: "Air Quality",
        icon: "🌫️",
        color: "#facc15",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-air", name: "PM2.5 by city", color: "#facc15", visible: true, features: [] },
        ],
      },
      {
        id: NUKETEST_ID,
        name: "Nuclear Tests",
        icon: "☢️",
        color: "#ef4444",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [80, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-nuketests", name: "Tests 1945–1998", color: "#ef4444", visible: true, features: [] },
        ],
      },
      {
        id: CO2_ID,
        name: "CO₂ Emissions",
        icon: "🏭",
        color: "#fb923c",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-co2", name: "CO₂ by country", color: "#fb923c", visible: true, features: [] },
        ],
      },
    ],
  };
}
