import type { AppData } from "./types";
import {
  EVERYTHING_ID,
  INBOX_ID,
  AIRCRAFT_ID,
  SHIPS_ID,
  RAIN_ID,
  ISS_ID,
  WORLD_ID,
  LIGHTNING_ID,
  METEORITE_ID,
} from "./types";

// Initial data on first run (while localStorage is empty). A showcase of the
// live/data layers plus a few empty demo workspaces and one example folder.
export function seedData(): AppData {
  return {
    activeWorkspaceId: EVERYTHING_ID,
    everythingStyle: "standard",
    workspaces: [
      {
        id: INBOX_ID,
        name: "Inbox",
        icon: "📥",
        color: "#868e96",
        style: "dark-v11",
        pinned: false,
        marker: "circle",
        center: [0, 20],
        zoom: 1.5,
        layers: [
          { id: "lyr-inbox", name: "Notes", color: "#868e96", visible: true, features: [] },
        ],
      },
      {
        id: AIRCRAFT_ID,
        name: "Live Aircraft",
        icon: "✈️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-aircraft", name: "Flights", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: SHIPS_ID,
        name: "Live Ships",
        icon: "🚢",
        color: "#15aabf",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [4, 52],
        zoom: 7,
        layers: [
          { id: "lyr-ships", name: "Vessels", color: "#15aabf", visible: true, features: [] },
        ],
      },
      {
        id: RAIN_ID,
        name: "Rain",
        icon: "🌧️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-rain", name: "Radar", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: ISS_ID,
        name: "Space Station",
        icon: "🛰️",
        color: "#f783ac",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 2,
        layers: [
          { id: "lyr-iss", name: "ISS", color: "#f783ac", visible: true, features: [] },
        ],
      },
      {
        id: LIGHTNING_ID,
        name: "Lightning",
        icon: "⚡",
        color: "#facc15",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-lightning", name: "Strikes", color: "#facc15", visible: true, features: [] },
        ],
      },
      {
        id: METEORITE_ID,
        name: "Meteorites",
        icon: "☄️",
        color: "#f59e0b",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-meteorites", name: "Landings", color: "#f59e0b", visible: true, features: [] },
        ],
      },
      {
        id: WORLD_ID,
        name: "World Data",
        icon: "🌍",
        color: "#22a884",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-world", name: "Countries", color: "#22a884", visible: true, features: [] },
        ],
      },
      {
        id: "ws-food",
        name: "Food",
        icon: "🍔",
        color: "#e8590c",
        style: "dark-v11",
        pinned: true,
        marker: "square",
        center: [37.6173, 55.7558],
        zoom: 12,
        layers: [
          { id: "lyr-food", name: "Places", color: "#e8590c", visible: true, features: [] },
        ],
      },
      {
        id: "ws-crashes",
        name: "Plane Crashes",
        icon: "✈️",
        color: "#c92a2a",
        style: "satellite-streets-v12",
        pinned: false,
        marker: "diamond",
        center: [10, 50],
        zoom: 4,
        layers: [
          { id: "lyr-crashes", name: "Incidents", color: "#c92a2a", visible: true, features: [] },
        ],
      },
      {
        id: "ws-drone",
        name: "Drone Notes",
        icon: "🚁",
        color: "#1971c2",
        style: "satellite-streets-v12",
        pinned: false,
        marker: "pin",
        center: [30.5234, 50.4501],
        zoom: 13,
        layers: [
          { id: "lyr-drone", name: "Text labels", color: "#1971c2", visible: true, features: [] },
        ],
      },
      {
        // Example folder: aggregates member spaces into one view.
        id: "folder-places",
        name: "Places",
        icon: "📁",
        color: "#845ef7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        members: ["ws-food"],
        center: [20, 50],
        zoom: 4,
        layers: [],
      },
    ],
  };
}
