import type { AppData } from "./types";
import {
  INBOX_ID,
  AIRCRAFT_ID,
  SHIPS_ID,
  RAIN_ID,
  ISS_ID,
  FIRE_ID,
  LIGHTNING_ID,
  METEORITE_ID,
  CABLE_ID,
  COVID_ID,
  NUCLEAR_ID,
} from "./types";

// Initial data on first run (while localStorage is empty). A showcase of the
// live/data layers plus a couple of empty demo workspaces.
export function seedData(): AppData {
  return {
    activeWorkspaceId: METEORITE_ID,
    workspaces: [
      {
        id: INBOX_ID,
        name: "Inbox",
        icon: "📥",
        color: "#868e96",
        style: "dark-v11",
        pinned: false,
        marker: "circle",
        center: [0, 20],
        zoom: 1.5,
        layers: [
          { id: "lyr-inbox", name: "Notes", color: "#868e96", visible: true, features: [] },
        ],
      },
      {
        id: AIRCRAFT_ID,
        name: "Live Aircraft",
        icon: "✈️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-aircraft", name: "Flights", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: SHIPS_ID,
        name: "Live Ships",
        icon: "🚢",
        color: "#15aabf",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [4, 52],
        zoom: 7,
        layers: [
          { id: "lyr-ships", name: "Vessels", color: "#15aabf", visible: true, features: [] },
        ],
      },
      {
        id: RAIN_ID,
        name: "Rain",
        icon: "🌧️",
        color: "#4dabf7",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 50],
        zoom: 5,
        layers: [
          { id: "lyr-rain", name: "Radar", color: "#4dabf7", visible: true, features: [] },
        ],
      },
      {
        id: ISS_ID,
        name: "Space Station",
        icon: "🛰️",
        color: "#f783ac",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 2,
        layers: [
          { id: "lyr-iss", name: "ISS", color: "#f783ac", visible: true, features: [] },
        ],
      },
      {
        id: LIGHTNING_ID,
        name: "Lightning",
        icon: "⚡",
        color: "#facc15",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-lightning", name: "Strikes", color: "#facc15", visible: true, features: [] },
        ],
      },
      {
        id: METEORITE_ID,
        name: "Meteorites",
        icon: "☄️",
        color: "#f59e0b",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-meteorites", name: "Landings", color: "#f59e0b", visible: true, features: [] },
        ],
      },
      {
        id: FIRE_ID,
        name: "Wildfires",
        icon: "🔥",
        color: "#fb923c",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 25],
        zoom: 1.6,
        layers: [
          { id: "lyr-fires", name: "Active fires", color: "#fb923c", visible: true, features: [] },
        ],
      },
      {
        id: CABLE_ID,
        name: "Submarine Cables",
        icon: "🌐",
        color: "#22d3ee",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [0, 20],
        zoom: 1.6,
        layers: [
          { id: "lyr-cables", name: "Cables", color: "#22d3ee", visible: true, features: [] },
        ],
      },
      {
        id: COVID_ID,
        name: "COVID-19",
        icon: "🦠",
        color: "#dc2626",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 25],
        zoom: 1.6,
        layers: [
          { id: "lyr-covid", name: "Cases by country", color: "#dc2626", visible: true, features: [] },
        ],
      },
      {
        id: NUCLEAR_ID,
        name: "Nuclear Plants",
        icon: "☢️",
        color: "#4ade80",
        style: "dark-v11",
        pinned: true,
        marker: "circle",
        center: [10, 30],
        zoom: 1.6,
        layers: [
          { id: "lyr-nuclear", name: "Reactors", color: "#4ade80", visible: true, features: [] },
        ],
      },
      {
        id: "ws-crashes",
        name: "Plane Crashes",
        icon: "✈️",
        color: "#c92a2a",
        style: "satellite-streets-v12",
        pinned: false,
        marker: "diamond",
        center: [10, 50],
        zoom: 4,
        layers: [
          { id: "lyr-crashes", name: "Incidents", color: "#c92a2a", visible: true, features: [] },
        ],
      },
      {
        id: "ws-drone",
        name: "Drone Notes",
        icon: "🚁",
        color: "#1971c2",
        style: "satellite-streets-v12",
        pinned: false,
        marker: "pin",
        center: [30.5234, 50.4501],
        zoom: 13,
        layers: [
          { id: "lyr-drone", name: "Text labels", color: "#1971c2", visible: true, features: [] },
        ],
      },
    ],
  };
}
